### PR TITLE
New: Add reference line via 'markdate' parameter

### PR DESCRIPTION
**Pull request by pawelsikora**
Adding reference line (color black) that can be used as additional point
in time on a chart. It can help with tracking tasks through setting the
date that has specific meaning for the user. Line will be drawn on a chart
when 'markdate' parameter will be defined with an appropriate 'date' argument.

Signed-off-by: Pawel Sikora pawel.sikora@nokia.com

Thanks Chris for your previous notes and requested changes. Keyword 'markdate'
sounds to be more informative than 'ref', so I change the name to this one, as you proposed ;)
Next thing is if in tutorial there is enough what I added? I wasn't sure what I need to write
additionally. Thanks in advance! (and sorry for late feedback, caused by some work and
personal things :P )

### CODE REVIEW

**Comment by pawelsikora** [comment]
Hi Chris,

Kind reminder ;)

KR,
Pawel

**Comment by jostber** [comment]
This looks like an interesting and useful feature. Would like to see this implemented.

**Comment by pawelsikora** [comment]
Up

**Comment by pawelsikora** [comment]
@scrapper

Chris, is there any chance that you will look on this?

Thanks & KR,
Pawel Sikora

**Comment by obeny** [comment]
Hi Chris, do you plan to merge it into master?
It would be great.

Thanks,
Marcin

**Comment by xypiie** [comment]
Hi  Chris,

could you please consider to merge it into master.

Thanks and kind regards,
--peter;

**Comment by jostber** [comment]
This is a popular one. Will this be included? :)

**Comment by jostber** [comment]
Bump. :)

**Comment by scrapper** [comment]
Sorry for ignoring the pull request that long. I've merged it now. Thanks for the contribution!

**Comment by pawelsikora** [comment]
Quiet a long time... ;) I managed yo completely forget about that. I hope it will still have some value to others... Thanks Chris and take care!

**Pull request merged**
